# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '2.x'
    includePreviewVersions: true

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFiles@2
  displayName: 'Copy built content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/dist
    cleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy deployment file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    contents: 'deploy.json'
    targetFolder: $(Build.ArtifactStagingDirectory)/development
    cleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Tennant-MIF-DevOps-Pipeline'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --destination $web --source $(Build.ArtifactStagingDirectory) --account-key nayeemtestiothublogs --account-name nayeemtestiothublogs'


